services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules:/etc/prometheus/rules
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.8.2
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
      - ./loki/wal:/loki/wal
      - ./loki/index:/loki/index
    ports:
      - "3100:3100"

  fluent-bit:
    image: fluent/fluent-bit:latest
    depends_on:
      - loki
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager:latest
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./alert-rules/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"