server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs from alert receiver
  - job_name: alert-receiver-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: alert-receiver
          __path__: /app/logs/alerts.log

  # Logs from NGINX (real service simulation)
  - job_name: nginx-real
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /app/nginx/access.log
