global:
  scrape_interval: 15s    # Har 15 seconds mein data collect karega
rule_files:
  - /etc/prometheus/rules/alerts.yml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'myapp'
    static_configs:
      - targets: ['myapp:9100']  # Aapki application agar port 9100 pe metrics